feat: add GameClient#advanceTo()
akashic-games/headless-akashic pull request #3
Opened 2021-03-19 05:08 UTC by yu-ogi

## このPullRequestが解決する内容
`GameClient#advanceTo()` を追加します。

このメソッドは引数に指定した条件に一致するまでゲームの状態を進行します。このメソッドにより、ユーザコンテンツの最初のシーン (≠ akashic-engine の initial scene) の読み込みまでゲームを進行することができるようになります。また、最初のシーンに限らず任意のタイミングまで進めることも可能になります。

2021-03-19 05:15 UTC, yu-ogi commented on src/__tests__/fixtures/helloworld/script/main.js
> +        assetIds: ["player", "shot", "se", "dummy_text"]
現時点では headless-driver は画像・音声アセットの読み込みに対応していませんでした。そのため、ダミーのテキストアセットを追加して非同期によるアセット読み込みの動作確認を行うように修正しました。

2021-03-19 05:20 UTC, yu-ogi commented on src/GameClient.ts
> +	async advanceTo(condition: GameClientConditionFunc, timeout: number = 5000): Promise<void> {
シーン読み込みタイミングを通知するトリガーを新設することも検討しましたが、このレイヤーで細かいロジックを持ってしまっても保守が大変になりそうなので、より汎用的な処理を追加してみました。

2021-03-19 07:51 UTC, xnv requested changes

2021-03-19 07:51 UTC, xnv commented on src/GameClient.ts
> +	async advanceTo(condition: GameClientConditionFunc, timeout: number = 5000): Promise<void> {
良案と思います。

しかし "advance to" と言われると個人的には「ここまで進む！」と言うような、 "ゴール" が明確な印象を受けます。 一方 `timeout` があることを見ても、この関数はむしろ「条件が満たされるまで "待つ"」ものに思えますから、たとえば `waitUntil()` とか呼ぶのはどうでしょうか。

参考: Unity の `WaitUntil()` https://docs.unity3d.com/jp/current/ScriptReference/WaitUntil.html

2021-03-19 07:51 UTC, xnv commented on README.md
> +    return game.scene().name === "..." // 最初のシーンをロードするまで進める
「最初の」かどうかはコンテンツに依存すると思います。説明をつけるなら「名前が `"..."` であるシーンに遷移するまで待つ」とかにしませんか。

2021-03-19 12:22 UTC, dera- commented on src/__tests__/fixtures/helloworld/text/dummy_text.txt
> +ilJg3P8BUssUy2rXbHA35QggtZJx+1047O9HFwrWUy/x3bFEQb5dvta6VHD0Jx0tw61/z0kzYEUJr6vjPq/rYz2oeK3yUgNfF4ZF
テストコンテンツでのみ使うものですし問題ないと思いますが、結構な量のファイルですね。。実際のテキストアセットもこれくらいのサイズになるということですかね

2021-03-19 12:26 UTC, dera- approved these changes
コメントしましたがapproveします

2021-03-22 05:30 UTC, yu-ogi commented on src/GameClient.ts
> +	async advanceTo(condition: GameClientConditionFunc, timeout: number = 5000): Promise<void> {
すごく悩ましいのですが、 `GameContext` および `GameClient`はゲームが停止している状態がデフォルトでして、外部から `step()` や `advance()` を呼び出すことでゲームを進行するようなモデルになっています。なので wait という用語を用いるとあたかも「ゲーム状態が常に進行している」ようにミスリードされてしまうのではないかと懸念しています。 
一方、to についてはたしかに仰るとおりなので (timeout はメソッド名の命名後につけた引数です) `advanceUntil()`でどうでしょうか。

2021-03-22 05:32 UTC, yu-ogi commented on src/__tests__/fixtures/helloworld/text/dummy_text.txt
> +ilJg3P8BUssUy2rXbHA35QggtZJx+1047O9HFwrWUy/x3bFEQb5dvta6VHD0Jx0tw61/z0kzYEUJr6vjPq/rYz2oeK3yUgNfF4ZF
テスト用なのでなるべくロード時間を稼ぐために少し大きめのテキストファイルにしました。

> 実際のテキストアセットもこれくらいのサイズになるということですかね

コンテンツによりそうですが、ss2asa 経由で少し凝った SpriteStudio のアニメーションデータを読み込むとこれくらいにはなるかもしれませんね。

2021-03-22 05:35 UTC, yu-ogi commented on README.md
> +    return game.scene().name === "..." // 最初のシーンをロードするまで進める
たしかにそうですね。こちら修正しました。

2021-03-23 07:14 UTC, xnv commented on src/GameClient.ts
> +	async advanceTo(condition: GameClientConditionFunc, timeout: number = 5000): Promise<void> {
なるほどです。 `advanceUntil()` 同意です。

2021-03-23 07:35 UTC, yu-ogi commented on src/GameClient.ts
> +	async advanceTo(condition: GameClientConditionFunc, timeout: number = 5000): Promise<void> {
3fbf7a0 `advanceUntil()` にリネームしました。

2021-03-24 03:04 UTC, xnv approved these changes

2021-03-24 03:40 UTC, merged